# Generated by Django 5.2.3 on 2026-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', '-status'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='is_approve',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customorder',
            name='color',
            field=models.CharField(blank=True, choices=[('Черный', 'Черный'), ('Белый', 'Белый'), ('Коричневый', 'Коричневый'), ('Темно-коричневый', 'Темно-коричневый'), ('Бежевый', 'Бежевый'), ('Карамель', 'Карамель'), ('Бордовый', 'Бордовый'), ('Вишневый', 'Вишневый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Темно-синий', 'Темно-синий'), ('Серый', 'Серый'), ('Антрацит', 'Антрацит'), ('Оливковый', 'Оливковый'), ('Хаки', 'Хаки'), ('Зеленый', 'Зеленый'), ('Желтый', 'Желтый'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Фиолетовый', 'Фиолетовый'), ('Песочный', 'Песочный'), ('Коньячный', 'Коньячный'), ('Терракотовый', 'Терракотовый'), ('-', 'Не выбран')], default='-', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('cdek', 'СДЭК'), ('yandex', 'Яндекс.Доставка'), ('courier', 'Курьер'), ('russian_post', 'Почта России')], default='courier', max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code_generated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата генерации кода'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('-', 'Новый'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='-', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Черный', 'Черный'), ('Белый', 'Белый'), ('Коричневый', 'Коричневый'), ('Темно-коричневый', 'Темно-коричневый'), ('Бежевый', 'Бежевый'), ('Карамель', 'Карамель'), ('Бордовый', 'Бордовый'), ('Вишневый', 'Вишневый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Темно-синий', 'Темно-синий'), ('Серый', 'Серый'), ('Антрацит', 'Антрацит'), ('Оливковый', 'Оливковый'), ('Хаки', 'Хаки'), ('Зеленый', 'Зеленый'), ('Желтый', 'Желтый'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Фиолетовый', 'Фиолетовый'), ('Песочный', 'Песочный'), ('Коньячный', 'Коньячный'), ('Терракотовый', 'Терракотовый'), ('-', 'Не выбран')], default='-', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина (см)'),
        ),
    ]
