# Generated by Django 5.2.3 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cartitem_unique_together_cartitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_stock', 'В наличии'),
                    ('out_of_stock', 'Нет в наличии'),
                    ('preorder', 'Предзаказ'),
                    ('discontinued', 'Снят с производства'),
                ],
                default='in_stock',
                max_length=50,
                verbose_name='Статус товара',
            ),
        ),
    ]
