# Dockerfile для использования пребилженного фронтенда
FROM node:20-alpine

WORKDIR /app

# Копируем package.json для установки production зависимостей
COPY package.json package-lock.json* ./

# Устанавливаем только production зависимости
RUN npm ci --omit=dev

# Копируем уже собранный .next и public
COPY .next ./.next
COPY public ./public

EXPOSE 3000

CMD ["npm", "start"]
